" Basic Settings
set showmatch           " highlight matching parentheses / brackets [{()}]
set mouse=a             " enable mouse support
set laststatus=2        " always show statusline (even with only single window)
set ruler               " show line and column number of the cursor on right side of statusline

" Syntax Highlighting
syntax on
filetype plugin indent on

" Tabs
set tabstop=4           " width that a <TAB> character displays as
set expandtab           " convert <TAB> key-presses to spaces
set shiftwidth=4        " number of spaces to use for each step of (auto)indent
set softtabstop=4       " backspace after pressing <TAB> will remove up to this many spaces

set autoindent          " copy indent from current line when starting a new line
set smartindent         " even better autoindent (e.g. add indent after '{')

" Search enhancements
set ignorecase
set smartcase
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
